### PR TITLE
fix: minor bug fixes

### LINKED ISSUE #18: "Listing Type" is not an available Sort By option at editor page load
As described in https://github.com/Automattic/newspack-listings/pull/12#pullrequestreview-553016114, the Listing Type sort option should be available by default, but currently you must interact with the "Listing Type" option first before it appears in the dropdown.

### PR DESCRIPTION
**Pull request by dkoo**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes two minor bugs:

1. When syncing metadata, avoid a PHP warning when the `single` key is not set in the metadata config array. This happens when syncing metadata that supports syncing data from multiple instances of a block, and the metadata config array in the newspack-listings-core.php file doesn't include the `'single' key.
2. When creating a new list in Query mode, "Listing Type" is now available as a default Sort By option (as "Any" is the default listing type).

Closes #18.

#### Testing the meta sync bug

1. Start out on the `master` branch.
2. Create a new Event listing post and add an a.) Event Dates block and b.) more than one Jetpack Contact Info block. Fill in data for all blocks.
3. Attempt to save or publish the post, and observe a PHP warning like `PHP Notice:  Undefined index: single in /Users/dkoo/Local Sites/newspack/app/public/wp-content/plugins/newspack-listings/includes/newspack-listings-utils.php on line 141` that prevents the post from being saved.
4. Check out this branch and run `npm run build`.
5. Attempt to save or publish the post again, confirm that the PHP warning does not occur and the post is saved successfully. Reload the post and confirm that your data has been actually saved.

#### Testing the Sort By option

1. Create a new Curated List block and choose Query mode.
2. Under Query Settings, expand "Show advanced filters" and observe that the "Sort By" dropdown include a Listing Type option.
3. Set the "Listing Type" option to something other than "Any" and confirm that "Sort By" option no longer includes the Listing Type option.
4. Set "Listing Type" to "Any" again and confirm once more that the "Sort By" dropdown include a Listing Type option.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

File: includes/newspack-listings-utils.php [hunk 1]
```diff
@@ -107,7 +107,7 @@ function get_data_from_blocks( $blocks, $source ) {
 		}
 
 		// If the source has 'single' specified, only get data from the first found block instance.
-		if ( $source['single'] ) {
+		if ( isset( $source['single'] ) && ! empty( $source['single'] ) ) {
```
Comment (jeffersonrabb) [inline includes/newspack-listings-utils.php:110]: I think you only need `! empty()` here - the `isset` check is unnecessary.

**Review by jeffersonrabb — APPROVED** [review]

File: includes/newspack-listings-utils.php (hunk 1 above)
Comment (dkoo) [reply includes/newspack-listings-utils.php]: Confirmed and updated in b8a76e0. Guess I wanted to be *extra* certain :)
